/**
 * QA 2.2 Linked Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Qa22LinkedDataApi);
  }
}(this, function(expect, Qa22LinkedDataApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Qa22LinkedDataApi.FetchTermApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FetchTermApi', function() {
    describe('gETFetchByIDFromAuthority', function() {
      it('should call gETFetchByIDFromAuthority successfully', function(done) {
        //uncomment below and update the code to test gETFetchByIDFromAuthority
        //instance.gETFetchByIDFromAuthority(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('gETFetchByIDFromSubauthority', function() {
      it('should call gETFetchByIDFromSubauthority successfully', function(done) {
        //uncomment below and update the code to test gETFetchByIDFromSubauthority
        //instance.gETFetchByIDFromSubauthority(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('gETFetchURIFromAuthority', function() {
      it('should call gETFetchURIFromAuthority successfully', function(done) {
        //uncomment below and update the code to test gETFetchURIFromAuthority
        //instance.gETFetchURIFromAuthority(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('oPTIONSFetchFromAuthority', function() {
      it('should call oPTIONSFetchFromAuthority successfully', function(done) {
        //uncomment below and update the code to test oPTIONSFetchFromAuthority
        //instance.oPTIONSFetchFromAuthority(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('oPTIONSFetchFromAuthority_0', function() {
      it('should call oPTIONSFetchFromAuthority_0 successfully', function(done) {
        //uncomment below and update the code to test oPTIONSFetchFromAuthority_0
        //instance.oPTIONSFetchFromAuthority_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('oPTIONSFetchFromSubauthority', function() {
      it('should call oPTIONSFetchFromSubauthority successfully', function(done) {
        //uncomment below and update the code to test oPTIONSFetchFromSubauthority
        //instance.oPTIONSFetchFromSubauthority(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
