/**
 * QA 2.2 Linked Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'api/AuthorityManagementApi', 'api/FetchTermApi', 'api/SearchQueryApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./api/AuthorityManagementApi'), require('./api/FetchTermApi'), require('./api/SearchQueryApi'));
  }
}(function(ApiClient, AuthorityManagementApi, FetchTermApi, SearchQueryApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Qa22LinkedDataApi = require('index'); // See note below*.
   * var xxxSvc = new Qa22LinkedDataApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Qa22LinkedDataApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Qa22LinkedDataApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Qa22LinkedDataApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 2.2
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AuthorityManagementApi service constructor.
     * @property {module:api/AuthorityManagementApi}
     */
    AuthorityManagementApi: AuthorityManagementApi,
    /**
     * The FetchTermApi service constructor.
     * @property {module:api/FetchTermApi}
     */
    FetchTermApi: FetchTermApi,
    /**
     * The SearchQueryApi service constructor.
     * @property {module:api/SearchQueryApi}
     */
    SearchQueryApi: SearchQueryApi
  };

  return exports;
}));
