// Copyright 2019 Stanford University see LICENSE for license

import React, { Component } from 'react'
import PropTypes from 'prop-types'
import { connect } from 'react-redux'
import Config from 'Config'
import CognitoUtils from 'utilities/CognitoUtils'
import { selectAuthenticationError, selectCurrentSession, selectCurrentUser } from 'selectors/authenticate'
import { authenticationFailed, authenticationSucceeded } from 'actionCreators/authenticate'

class LoginPanel extends Component {
  constructor(props) {
    super(props)
    this.state = {}

    /*
     * If the Cognito user info was just retrieved from local storage, as when the app first
     * loads, the session info we need won't be present on it.  However, the associated id,
     * access, and refresh tokens are all saved in local storage also. As such, the getSession()
     * method will attempt to use the refresh token (if present) to get new id and access tokens.
     */

    const currentUser = this.props.currentUser || CognitoUtils.cognitoUserPool().getCurrentUser()
    const currentSession = this.props.currentSession

    if (currentUser && !currentSession) {
      CognitoUtils.getSession(currentUser)
        .then((sessionData) => {
          this.props.authenticate({ currentUser, currentSession: sessionData })
        }).catch((errInfo) => {
          this.props.failToAuthenticate({ currentUser, authenticationError: errInfo })
        })
    }
  }

  handleLoginSubmit = (event) => {
    event.preventDefault()

    const cognitoUser = CognitoUtils.cognitoUser(this.state.username)

    CognitoUtils.authenticateUser(cognitoUser, this.state.password)
      .then((cognitoUserSession) => {
        this.props.authenticate({ currentUser: cognitoUser, currentSession: cognitoUserSession })
      }).catch((errInfo) => {
        this.props.failToAuthenticate({ currentUser: cognitoUser, authenticationError: errInfo })
      })
  }

  handleChange = (event) => {
    this.setState({ [event.target.name]: event.target.value })
  }

  render() {
    const currentSession = this.props.currentSession
    const authenticationError = this.props.authenticationError

    const inlineLoginForm = (
      <React.Fragment>
        <h4>Login to the Linked Data Editor</h4>
        <div className = "form-group">
          <label htmlFor="username">
            User name
            <input id="username"
                   style={ { width: '300px' } }
                   name="username" type="text"
                   className="form-control"
                   placeholder=""
                   onChange={this.handleChange}></input>
          </label>
        </div>
        <div className = "form-group">
          <label htmlFor="password">
            Password
            <input id="password"
                   style={ { width: '300px' } }
                   name="password"
                   type="password"
                   className="form-control"
                   placeholder=""
                   onChange={this.handleChange}></input>
          </label>
        </div>
        <div className="row">
          <div className="col-sm-4">
            <button className="btn btn-block btn-primary" type="submit">Login</button>
          </div>
          <div className="col-sm-4">
            <div className="row">
              <a href={Config.awsCognitoForgotPasswordUrl}>Forgot Password</a>
            </div>
            <div className="row">
              <a href={Config.awsCognitoResetPasswordUrl}>Request Account</a>
            </div>
          </div>
        </div>
      </React.Fragment>
    )

    const loginErrorMessageElement = (
      <React.Fragment>
        {
          authenticationError
            && <div className="alert alert-danger alert-dismissible" role="alert" aria-label={ authenticationError.message }>{ authenticationError.message }</div>
        }
      </React.Fragment>
    )

    return (
      <React.Fragment>
        { loginErrorMessageElement }
        <form className="login-form" onSubmit={this.handleLoginSubmit}>
          { !currentSession && inlineLoginForm }
        </form>
      </React.Fragment>
    )
  }
}

LoginPanel.propTypes = {

  /*
   * Separate props for currentUser, currentSession, authenticationError.  see https://redux.js.org/faq/react-redux#why-is-my-component-re-rendering-too-often
   *   "React Redux implements several optimizations to ensure your actual component only re-renders when actually necessary. One of those is a shallow equality
   *   check on the combined props object generated by the mapStateToProps and mapDispatchToProps arguments passed to connect. Unfortunately, shallow equality does
   *   not help in cases where new array or object instances are created each time mapStateToProps is called."
   */
  currentUser: PropTypes.object,
  currentSession: PropTypes.object,
  authenticationError: PropTypes.object,
  failToAuthenticate: PropTypes.func,
  authenticate: PropTypes.func,
  signout: PropTypes.func,
}

const mapStateToProps = (state) => ({
  currentUser: selectCurrentUser(state),
  currentSession: selectCurrentSession(state),
  authenticationError: selectAuthenticationError(state),
})

export default connect(
  mapStateToProps,
  {
    failToAuthenticate: authenticationFailed,
    authenticate: authenticationSucceeded,
  },
)(LoginPanel)
