/**
 * QA 2.2 Linked Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Qa22LinkedDataApi) {
      root.Qa22LinkedDataApi = {};
    }
    root.Qa22LinkedDataApi.AuthorityManagementApi = factory(root.Qa22LinkedDataApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * AuthorityManagement service.
   * @module api/AuthorityManagementApi
   * @version 2.2
   */

  /**
   * Constructs a new AuthorityManagementApi. 
   * @alias module:api/AuthorityManagementApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * List currently loaded linked data authorities
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.gETListAuthoritiesWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/list/linked_data/authorities', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * List currently loaded linked data authorities
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.gETListAuthorities = function() {
      return this.gETListAuthoritiesWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Reload linked data authorities.  Using this command avoids having to restart the rails server.
     * @param {String} authToken Security token which must be included for this command to execute.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.gETReloadAuthoritiesWithHttpInfo = function(authToken) {
      var postBody = null;

      // verify the required parameter 'authToken' is set
      if (authToken === undefined || authToken === null) {
        throw new Error("Missing the required parameter 'authToken' when calling gETReloadAuthorities");
      }


      var pathParams = {
      };
      var queryParams = {
        'auth_token': authToken,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/reload/linked_data/authorities', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Reload linked data authorities.  Using this command avoids having to restart the rails server.
     * @param {String} authToken Security token which must be included for this command to execute.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.gETReloadAuthorities = function(authToken) {
      return this.gETReloadAuthoritiesWithHttpInfo(authToken)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
